name: chair_store
description: mobile application - chair store

publish_to: 'none'

version: 0.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  flutter_secure_storage: ^7.0.1
  get_it: ^7.2.0
  flutter_native_splash: ^2.2.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true